package Perbankan;
import javax.swing.JOptionPane;
import Logic.Teller;
import Logic.Nasabah;

public class FrameTeller extends FrameDasar {

    /**
     * Creates new form Teller
     */
    public FrameTeller() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    FrameTeller(Nasabah nasabah){
        super(nasabah);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCekSaldo = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnTarikTunai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDeposit1 = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnCekSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCekSaldo.setText("Cek Saldo");
        btnCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekSaldoActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnTarikTunai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTarikTunai.setText("Tarik Tunai");
        btnTarikTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikTunaiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TELLER");

        btnDeposit1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeposit1.setText("Deposit");
        btnDeposit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeposit1ActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnTarikTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeposit1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(btnPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCekSaldo)
                    .addComponent(btnTarikTunai))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposit1)
                    .addComponent(btnTransfer))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeluar)
                    .addComponent(btnPembayaran))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekSaldoActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Rp " +getTellerControll().checkDeposit(),"Saldo Anda ", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCekSaldoActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        this.changeFrame(new MenuLogin());
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTarikTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikTunaiActionPerformed
       double uang = Double.parseDouble(JOptionPane.showInputDialog(rootPane,"Masukan Jumlah Yang Akan di Tarik","Tarik Tunai",JOptionPane.QUESTION_MESSAGE ));
       this.getTellerControll().withdraw(uang);
       JOptionPane.showMessageDialog(rootPane,"Rp "+this.getTellerControll().checkDeposit(),"Saldo Anda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTarikTunaiActionPerformed

    private void btnDeposit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeposit1ActionPerformed
       double uang = Double.parseDouble(JOptionPane.showInputDialog(rootPane,"Masukan Setoran Tunai Anda","Setor Tunai",JOptionPane.QUESTION_MESSAGE ));
       this.getTellerControll().saving(uang);
       JOptionPane.showMessageDialog(rootPane,"Rp "+this.getTellerControll().checkDeposit(),"Saldo Anda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeposit1ActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        String noRekTujuan = JOptionPane.showInputDialog(rootPane,"Masukan Nomor Rekening Tujuan","Transfer Uang",JOptionPane.QUESTION_MESSAGE);
        double jumlah = Double.parseDouble(JOptionPane.showInputDialog(rootPane,"Masukan Jumlah Transfer","Transfer Uang",JOptionPane.QUESTION_MESSAGE));
        Nasabah nasabahTujuan = this.getTellerControll().cekTransfer(noRekTujuan);
        this.getTellerControll().transfer(nasabahTujuan, jumlah);
        JOptionPane.showMessageDialog(null, "Saldo Anda Sekarang Rp "+this.getTellerControll().checkDeposit());
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        this.changeFrame(new PembayaranTeller(this.getNasabah()));
    }//GEN-LAST:event_btnPembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekSaldo;
    private javax.swing.JButton btnDeposit1;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnTarikTunai;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
