package Perbankan;
import javax.swing.JOptionPane;
import Logic.Teller;
import Logic.Nasabah;

public class PembayaranTeller extends FrameDasar {

    /**
     * Creates new form PembayaranTeller
     */
    public PembayaranTeller() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    PembayaranTeller(Nasabah nasabah){
        super(nasabah);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnListrik = new javax.swing.JButton();
        btnPDAM = new javax.swing.JButton();
        btnAsuransi = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Pembayaran Via Teller");

        btnListrik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListrik.setText("Listrik");
        btnListrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListrikActionPerformed(evt);
            }
        });

        btnPDAM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPDAM.setText("PDAM");
        btnPDAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDAMActionPerformed(evt);
            }
        });

        btnAsuransi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAsuransi.setText("Asuransi");
        btnAsuransi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsuransiActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAsuransi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPDAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(btnListrik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnListrik)
                .addGap(18, 18, 18)
                .addComponent(btnPDAM)
                .addGap(18, 18, 18)
                .addComponent(btnAsuransi)
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListrikActionPerformed
        double uang = Double.parseDouble(JOptionPane.showInputDialog(rootPane,"Masukan Jumlah Biaya Listrik","Bayar Listrik",JOptionPane.QUESTION_MESSAGE ));
        this.getTellerControll().bayar(uang);
        JOptionPane.showMessageDialog(rootPane,"Rp "+this.getTellerControll().checkDeposit(),"Saldo Anda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnListrikActionPerformed

    private void btnPDAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDAMActionPerformed
        double uang = Double.parseDouble(JOptionPane.showInputDialog(rootPane,"Masukan Jumlah Biaya PDAM","Bayar PDAM",JOptionPane.QUESTION_MESSAGE ));
        this.getTellerControll().bayar(uang);
        JOptionPane.showMessageDialog(rootPane,"Rp "+this.getTellerControll().checkDeposit(),"Saldo Anda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPDAMActionPerformed

    private void btnAsuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsuransiActionPerformed
        double uang = Double.parseDouble(JOptionPane.showInputDialog(rootPane,"Masukan Jumlah Biaya Asuransi","Bayar Asuransi",JOptionPane.QUESTION_MESSAGE ));
        this.getTellerControll().bayar(uang);
        JOptionPane.showMessageDialog(rootPane,"Rp "+this.getTellerControll().checkDeposit(),"Saldo Anda",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAsuransiActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.changeFrame(new FrameTeller(this.getNasabah()));
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembayaranTeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsuransi;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnListrik;
    private javax.swing.JButton btnPDAM;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
